default: &default
  adapter: mysql2
  encoding: utf8mb4
  database: jagi
  username: root
  password: 
  host: localhost

development:
  <<: *default
  database: jagi_development

test:
  <<: *default
  database: jagi_test

production:
  adapter: mysql2
  encoding: utf8mb4
  database: jagi
  username: root
  password: 
  host: localhost
